/*
@nodoc excluded from html generator
*/

/**********************************************************************************/
/* Qualifier and option description                                               */
/**********************************************************************************/
static struct optHelp recm_help_options[]=
{
   {CMD_BACKUPCFG,        "tag",           "Define custom keyword to backup."},
   {CMD_BACKUPCFG,        "lock",          "Lock backup from deletion and obsolescence."},

   {CMD_BACKUPFULL,       "cleanup",       "Execute \'delete backup/obsolete\' after backup."},
   {CMD_BACKUPFULL,       "directory",     "Change default backup destination."},
   {CMD_BACKUPFULL,       "exclusive",     "Initiate an EXCLUSIVE backup."},
   {CMD_BACKUPFULL,       "lock",          "Lock backup from deletion and obsolescence."},
   {CMD_BACKUPFULL,       "noindex",       "Suppress indexes from backup."},
   {CMD_BACKUPFULL,       "parallel",      "Launch backup using threads [1..32]."},
   {CMD_BACKUPFULL,       "rp",            "Create a restore point (RP) at the end of the backup."},
   {CMD_BACKUPFULL,       "tag",           "Define custom keyword to backup."},
   {CMD_BACKUPFULL,       "verify",        "Execute \'verify backup\' after backup."},
   {CMD_BACKUPFULL,       "wal",           "Invoke WAL backup after backup."},
   
   {CMD_BACKUPMETA,       "database",      "Comma separated list of database to use(+) or/and exclude(-)\nExample:\n     '-sandbox' exclude 'sandbox' from the backup."},
   {CMD_BACKUPMETA,       "lock",          "Lock backup from deletion and obsolescence."},
   {CMD_BACKUPMETA,       "tag",           "Define custom keyword to backup."},
                          
   {CMD_BACKUPWAL,        "delete",        "Override configuration and remove WAL files after backup."},
   {CMD_BACKUPWAL,        "lock",          "Lock backup from deletion and obsolescence."},
   {CMD_BACKUPWAL,        "nochkpt",       "Do not perform CHECKPOINT when performing switch wal."},
   {CMD_BACKUPWAL,        "nodelete",      "Override configuration and leave WAL files on disk after backup."},
   {CMD_BACKUPWAL,        "parallel",      "Launch backup using threads [1..32]."},
   {CMD_BACKUPWAL,        "switch",        "invoke a 'CHECKPOINT' followed by a \'switch wal\' before to launch backup."},
   {CMD_BACKUPWAL,        "tag",           "Define custom keyword to backup."},
                          
   {CMD_CREATEDEPOSIT,    "database",      "Database Name of the DEPOSIT."},
   {CMD_CREATEDEPOSIT,    "force",         "Re-Create DEPOSIT even if it already exist."},
   {CMD_CREATEDEPOSIT,    "name",          "Give a name to the DEPOSIT."},
   {CMD_CREATEDEPOSIT,    "password",      "Password to connect to DEPOSIT."},
   {CMD_CREATEDEPOSIT,    "user",          "User and schema that will own the DEPOSIT."},
   
   {CMD_DELETECLUSTER,    "cid",           "Identify the cluster to delete by it's ID (See command 'list clusters')"},
   {CMD_DELETECLUSTER,    "includefiles",  "Delete a cluster and all backup files." },
   {CMD_DELETECLUSTER,    "force",         "Even if cluster is not 'disabled', delete the cluster"},

   {CMD_CREATERP,         "name",          "name of the restore point to create."},
   {CMD_CREATERP,         "permanent",     "Create PERMANENT restore point. This option prevent backup deletion."},
   {CMD_CREATERP,         "temporary",     "Create TEMPORARY restore point (Default)."},

   {CMD_CNXDEPOSIT,       "name",          "connect to a known DEPOSIT name (already used locally)."},
   
   {CMD_DELETEBACKUP,     "failed",        "Delete backups in \'FAILED\' state."},
   {CMD_DELETEBACKUP,     "incomplete",    "Delete backups in \'INCOMPLETE\' state."},
   {CMD_DELETEBACKUP,     "noremove",      "Do not delete physically backup files."},
   {CMD_DELETEBACKUP,     "obsolete",      "Delete backups in \'OBSOLETE\' state."},
   {CMD_DELETEBACKUP,     "uid",           "Delete specific backups (Multiple UID can be used, seprated by comman)."},
                          
   {CMD_DELETERP,         "name",          "Name of the restore point to delete."},
                          
   {CMD_LISTBACKUP,       "after",         "Filter on backup after the specified date."},
   {CMD_LISTBACKUP,       "available",     "Filter on \'AVAILABLE\' state."},
   {CMD_LISTBACKUP,       "before",        "Filter on backup before the specified date."},
   {CMD_LISTBACKUP,       "cfg",           "List only \'CONFIG\' backups."},
   {CMD_LISTBACKUP,       "cid",           "Display backups of an other cluster by it's ID."},
   {CMD_LISTBACKUP,       "full",          "List only \'FULL\' backups."},
   {CMD_LISTBACKUP,       "incomplete",    "Filter on \'INCOMPLETE\' state."},
   {CMD_LISTBACKUP,       "locked",        "Display locked backups"},
   {CMD_LISTBACKUP,       "meta",          "List only \'METAdata\' backups."},
   {CMD_LISTBACKUP,       "nocfg",         "Exclude \'CONFIG\' backups list."},
   {CMD_LISTBACKUP,       "nofull",        "Exclude \'FULL\' backups list."},
   {CMD_LISTBACKUP,       "nometa",        "Exclude \'METADATA\' from backups list."},
   {CMD_LISTBACKUP,       "nowal",         "Exclude \'WAL\' backups list."},
   {CMD_LISTBACKUP,       "obsolete",      "Filter on \'OBSOLETE\' state."},
   {CMD_LISTBACKUP,       "source",        "Display backups of an other cluster by it's name."},
   {CMD_LISTBACKUP,       "tag",           "Filter on custom keyword."},
   {CMD_LISTBACKUP,       "wal",           "List only \'WAL\' backups."},
                          
   {CMD_LISTWAL,          "available",     "Filter on \'AVAILABLE\' backups."},
   {CMD_LISTWAL,          "cid",           "Display WAL backups of an other cluster by it's ID."},
   {CMD_LISTWAL,          "incomplete",    "Filter on \'INCOMPLETE\' backups."},
   {CMD_LISTWAL,          "obsolete",      "Filter on \'OBSOLETE\' backups."},
   {CMD_LISTWAL,          "source",        "Display WAL backups of an other cluster by it's name."},
   {CMD_LISTWAL,          "uid",           "Display WAL from a specified backup."},
                          
   {CMD_LISTRP,           "cid",           "Display restore point of an other cluster by it's ID."},
   {CMD_LISTRP,           "nocid",         "Display restore point of all registered clusters."},
   {CMD_LISTRP,           "source",        "Display restore point of an other cluster by it's name."},

   {CMD_REGCLUSTER,       "cid",           "Give a specific CID to the cluster."},
   {CMD_REGCLUSTER,       "force",         "Force Register cluster."},
   {CMD_REGCLUSTER,       "ip",            "Give a specific IP address, instead of default."},

   {CMD_MODIFYCLUSTER,    "backupdir",     "Change Backup location"},
   {CMD_MODIFYCLUSTER,    "blksize",       "Modify blocksize for restoration"},
   {CMD_MODIFYCLUSTER,    "cfg",           "Modify Config backups retention"},
   {CMD_MODIFYCLUSTER,    "cid",           "Choose cluster to change by it ID."},
   {CMD_MODIFYCLUSTER,    "compression",   "Change compression level (-1 to disable compression)"},
   {CMD_MODIFYCLUSTER,    "concurrently",  "Change rebuild index 'concurrently' (for restore and duplicate)"},
   {CMD_MODIFYCLUSTER,    "date_format",   "Display only item 'date_format'"},
   {CMD_MODIFYCLUSTER,    "delwal",        "Delete backuped WAL files older than <minutes> (set '-1' to disable deletion)"},
   {CMD_MODIFYCLUSTER,    "description",   "Change cluster description"},
   {CMD_MODIFYCLUSTER,    "disable",       "Suspend backup operation on the cluster"},
   {CMD_MODIFYCLUSTER,    "enable",        "Permit backup operation on the cluster"},
   {CMD_MODIFYCLUSTER,    "full",          "Modify FULL/WALL backups retention"},
   {CMD_MODIFYCLUSTER,    "ip",            "Change cluster IP"},
   {CMD_MODIFYCLUSTER,    "meta",          "Modify meta data backups retention"},
   {CMD_MODIFYCLUSTER,    "maxfiles",      "Limit backup piece size by number of files"},
   {CMD_MODIFYCLUSTER,    "maxsize",       "Limit backup piece size"},
   {CMD_MODIFYCLUSTER,    "name",          "Choose cluster to change by it NAME."},
   {CMD_MODIFYCLUSTER,    "repopts",       "Change replication options"},
   {CMD_MODIFYCLUSTER,    "reppwd",        "Change replication user's password"},
   {CMD_MODIFYCLUSTER,    "repusr",        "Change replication user"},
   {CMD_MODIFYCLUSTER,    "waldir",        "Change WAL backup location(See 'archive-command' parameter)"},
                          
   {CMD_MODIFYBACKUP,     "available",     "Change backup status as 'available' ."},
   {CMD_MODIFYBACKUP,     "cid",           "Change backup of a different cluster ID."},
   {CMD_MODIFYBACKUP,     "incomplete",    "Change backup status as 'incomplete' ."},
   {CMD_MODIFYBACKUP,     "location",      "Modify the path where backup pieces are located (Files are not moved)."},
   {CMD_MODIFYBACKUP,     "lock",          "Suspend backup from deletion and obsolescence (keep a backup longer)."},
   {CMD_MODIFYBACKUP,     "obsolete",      "Change backup status as 'obsolete' ."},
   {CMD_MODIFYBACKUP,     "tag",           "Change backup TAG."},
   {CMD_MODIFYBACKUP,     "uid",           "Select backup UID to modify (Comma separated list allowed)."},
   {CMD_MODIFYBACKUP,     "unlock",        "Enable obsolescence and deletion of the backup."},
                
   {CMD_RESTOREWAL,       "after",         "Restore all WAL files after the specified date."},
   {CMD_RESTOREWAL,       "before",        "Restore all WAL files before the specified date."},
   {CMD_RESTOREWAL,       "directory",     "Restore all WAL files into a different folder."},   
   {CMD_RESTOREWAL,       "file",          "Restore a specific WAL file."},
   {CMD_RESTOREWAL,       "uid",           "Restore all WAL files from a specific backup UID."},
                                                                                             
   {CMD_RESTORECFG,       "after",         "Restore all files after the specified date."},
   {CMD_RESTORECFG,       "before",        "Restore all files before the specified date."},
   {CMD_RESTORECFG,       "directory",     "Restore all files into a different folder."},   
   {CMD_RESTORECFG,       "file",          "Restore a specific configuration file(s). The string follow 'regexp' expression."},
   {CMD_RESTORECFG,       "tag",           "Filter on 'tag' and Restore configuration files."},
   {CMD_RESTORECFG,       "uid",           "Restore all files from a specific backup UID."},
                         
   {CMD_RESTOREFULL,      "cid",           "ID of the SOURCE cluster"},
   {CMD_RESTOREFULL,      "directory",     "PGDATA of new cluster."},   
   {CMD_RESTOREFULL,      "inclusive",     "Recovery will stop just before the specified recovery target (recovery_target_inclusive is false)."},   
   {CMD_RESTOREFULL,      "lsn",           "Restore until Logical Sequence Number(LSN)."},
   {CMD_RESTOREFULL,      "newname",       "Give a name to the new new cluster."},
   {CMD_RESTOREFULL,      "noninclusive",  "Recovery will stop just after the specified recovery target (recovery_target_inclusive is true)."},   
   {CMD_RESTOREFULL,      "port",          "The restored instance will use this port"},
   {CMD_RESTOREFULL,      "rp",            "Restore until Restore Point Name."},
   {CMD_RESTOREFULL,      "source",        "Name of the SOURCE cluster"},
   {CMD_RESTOREFULL,      "uid",           "Backup UID of the full backup to use"},
   {CMD_RESTOREFULL,      "until",         "Restore until Date."},

   {CMD_RESTOREPARTIAL,   "cid",           "ID of the SOURCE cluster"},
   {CMD_RESTOREPARTIAL,   "db",            "Give the list of database to restore (default is all).\nExample:\n/database=\"demo,test\"  will restore databases 'demo' and 'test'."},
   {CMD_RESTOREPARTIAL,   "directory",     "PGDATA of new cluster."},   
   {CMD_RESTOREPARTIAL,   "inclusive",     "Recovery will stop just before the specified recovery target (recovery_target_inclusive is false)."},   
   {CMD_RESTOREPARTIAL,   "lsn",           "Restore until Logical Sequence Number(LSN)."},
   {CMD_RESTOREPARTIAL,   "newname",       "Give a name to the new new cluster."},
   {CMD_RESTOREPARTIAL,   "noninclusive",  "Recovery will stop just after the specified recovery target (recovery_target_inclusive is true)."},   
   {CMD_RESTOREPARTIAL,   "pause",         "At the end of Recovery, set recovery to 'pause' instead of 'promote' (recovery_target_action)"},
   {CMD_RESTOREPARTIAL,   "port",          "The restored instance will use this port"},
   {CMD_RESTOREPARTIAL,   "rp",            "Restore until Restore Point Name."},
   {CMD_RESTOREPARTIAL,   "schema",        "Give the list of schemas to restore (default is all)"},
   {CMD_RESTOREPARTIAL,   "source",        "Name of the SOURCE cluster"},
   {CMD_RESTOREPARTIAL,   "table",         "Give the list of database to restore (default is all)\nExample:\n /table=\"tab1,tab2,mytab*\" will restore the two tables tab1,tab2 and all tables that start with 'mytab'."},
   {CMD_RESTOREPARTIAL,   "until",         "Restore until Date."},
   {CMD_RESTOREPARTIAL,   "uid",           "Backup UID of the full backup to use"},

   {CMD_RESTOREFULL,      "inclusive",     "Recovery will stop just before the specified recovery target (recovery_target_inclusive is false)."},   
   {CMD_RESTOREFULL,      "noninclusive",  "Recovery will stop just after the specified recovery target (recovery_target_inclusive is true)."},   
   {CMD_RESTOREFULL,      "pause",         "At the end of Recovery, set recovery to 'pause' instead of 'promote' (recovery_target_action)"},

   {CMD_SETCONFIG,        "date_format",   "Change default date format."},
   {CMD_SETCONFIG,        "bindir",        "Specify the postgresql binary folder."},
   {CMD_SETCONFIG,        "history",       "In interactive mode, number of history commands to keep."},
   {CMD_SETCONFIG,        "prompt",        "Change prompt string."},
   {CMD_SETCONFIG,        "timezone",      "At restore time, you can set the default timezone (default is taken from the postgresql.conf file)"},

   {CMD_SETMAPPING,    "directory",     "New destination folder for the specified tablespace."},
   {CMD_SETMAPPING,    "force",         "Force creation of directory."},
   {CMD_SETMAPPING,    "reset",         "Clear all mapping definition."},
   {CMD_SETMAPPING,    "delete",        "Remove a mapping definition."},
   {CMD_SETMAPPING,    "tablespace",    "Tablespace name to remap."},

   {CMD_SETSOURCE,        "blksize",       "Modify blocksize for the restore/duplicate."},
   {CMD_SETSOURCE,        "directory",     "Use Different backup location."},
   
   {CMD_SHOWCONFIG,       "date_format",   "Display only item 'Date format'"},
   {CMD_SHOWCONFIG,       "bindir",        "Display only item 'postgreSQL binary directory'"},
   {CMD_SHOWCONFIG,       "history",       "Display only item 'Command line history'"},
   {CMD_SHOWCONFIG,       "prompt",        "Display only item 'Prompt string='"},
   {CMD_SHOWCONFIG,       "timezone",      "Display only item 'Default timezone'"},

   {CMD_SHOWCLUSTER,      "backupdir",     "Display only item 'backupdir"},
   {CMD_SHOWCLUSTER,      "blksize",       "Display only item 'blksize'"},
   {CMD_SHOWCLUSTER,      "cfg",           "Display only item 'cfg'"},
   {CMD_SHOWCLUSTER,      "compression",   "Display only item 'compression'"},
   {CMD_SHOWCLUSTER,      "concurrently",  "Display only item 'concurrently'"},
   {CMD_SHOWCLUSTER,      "date_format",   "Display only item 'date_format'"},
   {CMD_SHOWCLUSTER,      "db",            "Display only item 'database'"},
   {CMD_SHOWCLUSTER,      "delwal",        "Display only item 'delwal'"},
   {CMD_SHOWCLUSTER,      "description",   "Display only item 'description'"},
   {CMD_SHOWCLUSTER,      "full",          "Display only item 'full'"},
   {CMD_SHOWCLUSTER,      "maxfiles",      "Display only item 'maxfiles'"},
   {CMD_SHOWCLUSTER,      "maxsize",       "Display only item 'maxsize'"},
   {CMD_SHOWCLUSTER,      "meta",          "Display only item 'meta'"},
   {CMD_SHOWCLUSTER,      "name",          "Display only item 'name'"},
   {CMD_SHOWCLUSTER,      "pgdata",        "Display only item 'pgdata'"},
   {CMD_SHOWCLUSTER,      "port",          "Display only item 'port'"},
   {CMD_SHOWCLUSTER,      "pwd",           "Display only item 'password'"},
   {CMD_SHOWCLUSTER,      "usr",           "Display only item 'user'"},
   {CMD_SHOWCLUSTER,      "waldir",        "Display only item 'waldir'"},
   {CMD_SHOWCLUSTER,      "repusr",        "Display only replication user"},
   {CMD_SHOWCLUSTER,      "reppwd",        "Display only replication user's password"},
   {CMD_SHOWCLUSTER,      "repopts",       "Display only replication options"},

   {CMD_SHOWDEPOSIT,      "db",            "Display only item 'database'"},
   {CMD_SHOWDEPOSIT,      "description",   "Display only item 'description'"},
   {CMD_SHOWDEPOSIT,      "host",          "Display only item 'host'"},
   {CMD_SHOWDEPOSIT,      "name",          "Display only item 'name'"},
   {CMD_SHOWDEPOSIT,      "port",          "Display only item 'port'"},
   {CMD_SHOWDEPOSIT,      "pwd",           "Display only item 'password'"},
   {CMD_SHOWDEPOSIT,      "usr",           "Display only item 'user'"},
   {CMD_SHOWDEPOSIT,      "version",       "Display only item 'version'"},
   
   {CMD_MODIFYDEPOSIT,    "db",            "Modify database (Effective at next connection)."},
   {CMD_MODIFYDEPOSIT,    "description",   "Modify deposit description."},
   {CMD_MODIFYDEPOSIT,    "host",          "Modify hostname (Effective at next connection)."},
   {CMD_MODIFYDEPOSIT,    "port",          "Modify port (Effective at next connection)."},
   {CMD_MODIFYDEPOSIT,    "pwd",           "Modify password (Effective at next connection)."},
   {CMD_MODIFYDEPOSIT,    "session",       "Change configuration at session level, without saving for reuse."},
   {CMD_MODIFYDEPOSIT,    "usr",           "Modify user (Effective at next connection)."},

   {CMD_SETSOURCE,        "directory",     "Change,at session level, Backup location for restore"},
   {CMD_SETSOURCE,        "blksize",       "Change,at session level, allocation block size for restore"},
      
   {CMD_SWITCHWAL,        "nochkpt",       "Do not perform CHECKPOINT when performing switch wal."},

   {CMD_VERIFYBACKUP,     "after",         "Verify all backups after the specified date"},                                                          
   {CMD_VERIFYBACKUP,     "before",        "Verify all backups before the specified date"},
   {CMD_VERIFYBACKUP,     "uid",           "Verify a specific backup"},

   {CMD_SHOWBACKUP,       "directories",   "List Tablespace directories used by the cluster."},
   {CMD_SHOWBACKUP,       "files",         "List all backup piece name."},
   {CMD_SHOWBACKUP,       "indexes",       "List user indexes (must be used with '/verbose'."},
   {CMD_SHOWBACKUP,       "piece",         "List content of backup piece."},
   {CMD_SHOWBACKUP,       "tables",        "List user tables (must be used with '/verbose'."},
   {CMD_SHOWBACKUP,       "uid",           "List backup details."},

   {CMD_DUPLICATEFULL,     "cid",          "ID of the SOURCE cluster"},
   {CMD_DUPLICATEFULL,     "directory",    "PGDATA of new cluster."},
   {CMD_DUPLICATEFULL,     "inclusive",     "Recovery will stop just before the specified recovery target (recovery_target_inclusive is false)."},   
   {CMD_DUPLICATEFULL,     "newname",      "Give a name to the new new cluster."},
   {CMD_DUPLICATEFULL,     "noninclusive",  "Recovery will stop just after the specified recovery target (recovery_target_inclusive is true)."},   
   {CMD_DUPLICATEFULL,     "pause",         "At the end of Recovery, set recovery to 'pause' instead of 'promote' (recovery_target_action)"},
   {CMD_DUPLICATEFULL,     "port",         "The restored instance will use this port"},
   {CMD_DUPLICATEFULL,     "source",       "Name of the SOURCE cluster"},
   {CMD_DUPLICATEFULL,     "uid",          "Backup UID of the full backup to use"},
   {CMD_DUPLICATEFULL,     "until",        "Date of the restore"},

   {CMD_UPGRADEDEPOSIT,    "apply",        "Without this option, the upgrade is checked only.\nWith the '/apply' option, the upgrade of the deposit is applied."},
   
   {CMD_DUPLICATEPARTIAL,  "cid",          "ID of the SOURCE cluster"},
   {CMD_DUPLICATEPARTIAL,  "db",           "Give the list of database to restore (default is all).\nExample:\n/database=\"demo,test\"  will restore databases 'demo' and 'test'."},
   {CMD_DUPLICATEPARTIAL,  "directory",    "PGDATA of new cluster."},   
   {CMD_DUPLICATEPARTIAL,  "inclusive",    "Recovery will stop just before the specified recovery target (recovery_target_inclusive is false)."},   
   {CMD_DUPLICATEPARTIAL,  "lsn",          "Restore until Logical Sequence Number(LSN)."},
   {CMD_DUPLICATEPARTIAL,  "newname",      "Give a name to the new new cluster."},
   {CMD_DUPLICATEPARTIAL,  "noninclusive", "Recovery will stop just after the specified recovery target (recovery_target_inclusive is true)."},   
   {CMD_DUPLICATEPARTIAL,  "pause",        "At the end of Recovery, set recovery to 'pause' instead of 'promote' (recovery_target_action)"},
   {CMD_DUPLICATEPARTIAL,  "port",         "The restored instance will use this port"},
   {CMD_DUPLICATEPARTIAL,  "rp",           "Restore until Restore Point Name."},
   {CMD_DUPLICATEPARTIAL,  "schema",       "Give the list of schemas to restore (default is all)"},
   {CMD_DUPLICATEPARTIAL,  "source",       "Name of the SOURCE cluster"},
   {CMD_DUPLICATEPARTIAL,  "table",        "Give the list of database to restore (default is all)\nExample:\n /table=\"tab1,tab2,mytab*\" will restore the two tables tab1,tab2 and all tables that start with 'mytab'."},
   {CMD_DUPLICATEPARTIAL,  "until",        "Restore until Date."},
   {CMD_DUPLICATEPARTIAL,  "uid",          "UID of the full backup to use"},
   {0,NULL,NULL}
};
