static struct commands recm_commands[]=
{
   // ID                 Command                Options                                        Qualifier                                                                                                 Help text
   {CMD_BACKUPCFG,       "backup-config",       ",/verbose,/lock,",                                  
                                                ",/tag=S,",                                    
                                                "Launch backup of configuration files."},
   {CMD_BACKUPFULL,      "backup-full",         ",/exclusive,/verbose,/noindex,/verify,/cleanup,/wal,/lock,/rp,",            
                                                ",/tag=S,/directory=S,/parallel=N,", 
                                                "Launch backup FULL of the current connected cluster."},
   {CMD_BACKUPWAL,       "backup-wal",          ",/delete,/lock,/nochkpt,/nodelete,/switch,/verbose,",        
                                                ",/parallel=N,/tag=S,",                                                                                                "Launch backup of WAL."},
   {CMD_BACKUPMETA,      "backup-meta",         ",/lock,/verbose,",                                  
                                                ",/db=S,/tag=S,", 
                                                "Launch backup of METADATA. Use 'pg_dump' tool to generated sql dump files and create a backup set."},
   {CMD_CANCELBACKUP,    "cancel-backup",       ",/verbose,", 
                                                NULL,
                                                "Cancel any running backup."},
   {CMD_CLRSCR,          "clrscr",              NULL,
                                                NULL,
                                                "Clear the console screen (same as clear command)."},
   {CMD_CREATEDEPOSIT,   "create-deposit",      ",/force,/verbose,",
                                                ",/db=MS,/pwd=MS,/usr=MS,",
                                                "Create new Deposit schema into the current connected cluster."},
   {CMD_CREATERP,        "create-restore-point",",/permanent,/temporary,/verbose,",
                                                ",/name=S,",
                                                "Create a restore point (Call 'pg_create_restore_point')."},
   {CMD_CNXCLUSTER,      "connect-cluster",     NULL,
                                                ",/db=S,/host=MS,/port=MN,/pwd=S,/usr=MS,",
                                                "Connect to PostgreSQL server (cluster)."},
   {CMD_CNXDEPOSIT,      "connect-deposit",     NULL,
                                                ",/db=S,/host=S,/name=S,/port=N,/pwd=S,/usr=S,",
                                                "Connect to PostgreSQL server DEPOSIT."},
   {CMD_CNXTARGET,       "connect-target",      NULL,
                                                ",/name=MS,",
                                                "Connect to PostgreSQL cluster and it's registered deposit."},                                             
   {CMD_DELETEBACKUP,    "delete-backup",       ",/incomplete,/failed,/noremove,/obsolete,/verbose,",
                                                ",/after=D,/before=D,/uid=S,",
                                                "Delete backups, and optionally associated physical files."},
   {CMD_DELETECLUSTER,   "delete-cluster",      ",/includefiles,/force,/verbose,",
                                                ",/cid=MN,",
                                                "Remove a cluster from the deposit. The cluster must be 'DISABLED' first."},
   {CMD_DELMAPPING,      "delete-mapping",      NULL,
                                                ",/tablespace=S,",
                                                "Delete tablespace mapping definition."},
   {CMD_DELETERP,        "delete-restore-point",",/verbose,",
                                                ",/name=S,",
                                                "Delete restore point."},
   {CMD_DISCONCLU,       "disconnect-cluster",  NULL,
                                                NULL,
                                                "Close cluster connection"},
   {CMD_DISCONDEPO,      "disconnect-deposit",  NULL,
                                                NULL,                                                                                                       "Close deposit connection"},
   {CMD_DISCONAUX,       "disconnect-auxiliary",NULL,
                                                NULL,                                                                                                       "Close auxiliary connection"},
   {CMD_DUPLICATEFULL,   "duplicate-full",      ",/force,/inclusive,/nochkver,/noninclusive,/norecover,/pause,/standby,/verbose,/vacuum,",
                                                ",/cid=S,/directory=MS,/lsn=S,/newname=S,/port=MN,/rp=S,/source=S,/uid=S,/until=D,/options=S,",
                                                "Perform a duplicate full as a new cluster."},
   {CMD_DUPLICATEPARTIAL,"duplicate-partial",   ",/force,/inclusive,/norecover,/nochkver,/noninclusive,/paused,/standby,/verbose,/vacuum,",
                                                ",/cid=S,/db=S,/directory=S,/lsn=S,/newname=S,/port=N,/rp=S,/schema=S,/source=S,/table=S,/uid=S,/until=D,/options=S,",  
                                                "Perform a duplicate partial of databases,schemas or tables as a new cluster."},
   {CMD_EXIT,            "exit",                NULL,
                                                NULL,
                                                "Exit from RECM."},
   {CMD_EXPCFG,          "export-config",       ",/cluster,/deposit,",
                                                ",/file=S,",
                                                "Export configuration."},
   {CMD_HELP,            "help",                NULL,
                                                NULL,
                                                "Display short help."},
   {CMD_HISTORY,         "history",             NULL,
                                                NULL,
                                                "Display history commands."},
   {CMD_LISTBACKUP,      "list-backup",         ",/available,/cfg,/full,/incomplete,/locked,/meta,/nofull,/noindex,/nometa,/nowal,/nocfg,/obsolete,/verbose,/wal,", 
                                                ",/cid=N,/after=S,/before=S,/source=S,/tag=S,",
                                                "Display all backups ordered by creation time."},
   {CMD_LISTCLUSTER,     "list-clusters",       ",/verbose,",
                                                NULL,
                                                "Display list of known clusters in DEPOSIT."},
   {CMD_LISTMAPPING,     "list-mapping",        NULL,
                                                NULL,
                                                "List defined targets."},
   {CMD_LISTRP,          "list-restore-point",  ",/nocid,",
                                                ",/after=D,/before=D,/cid=N,/source=S,",
                                                "List restore point."},
   {CMD_LISTWAL,         "list-wal",            ",/available,/incomplete,/obsolete,",
                                                ",/before=D,/after=D,/uid=S,/source=S,/cid=N,",
                                                "List WAL files backuped."},
   {CMD_MODIFYBACKUP,    "modify-backup",       ",/available,/incomplete,/obsolete,/lock,/unlock,",
                                                ",/cid=S,/uid=MS,/tag=S,/location=S,",
                                                "Change backup properties."},
   {CMD_MODIFYCLUSTER,   "modify-cluster",      ",/enable,/disable,",
                                                ",/backupdir=S,/blksize=S,/db=S,/cfg=S,/cid=N,/compression=N,/concurrently=S,/date_format=S,/delwal=N,/description=S,/full=S,/ip=S,/maxfiles=N,/maxwalfiles=N,/maxsize=S,/maxwalsize=S,/meta=S,/name=S,/pwd=S,/port=S,/repopts=S,/reppwd=S,/repusr=S,/usr=S,/waldir=S,",
                                                "Change Cluster state."},
   {CMD_MODIFYDEPOSIT,   "modify-deposit",      ",/session,",                                  
                                                ",/db=S,/description=S,/host=S,/port=S,/pwd=S,/usr=S,",
                                                "Modify deposit properties."},
   {CMD_QUIT,            "quit",                NULL,
                                                NULL,
                                                "Exit from RECM."},
   {CMD_REGCLUSTER,      "register-cluster",    ",/force,",
                                                ",/cid=N,/ip=S,",
                                                "Register current cluster to the deposit."},
   {CMD_REGFILES,        "register-files",      ",/cfg,/full,/wal,/meta,/verbose,",
                                                ",/cid=N,/directory=S,",
                                                "Register old files into the deposit."},
   {CMD_RELOAD,          "reload",              NULL,
                                                NULL,
                                                "Reload configuration file."},
   {CMD_RESTOREWAL,      "restore-wal",         ",/verbose,",
                                                ",/after=S,/before=S,/cid=S,/directory=S,/file=S,/first=S,/last=S,/source=S,/uid=S,",
                                                "Restore WAL files."},
   {CMD_RESTORECFG,      "restore-config",      ",/verbose,/overwrite,",
                                                ",/cid=S,/file=S,/uid=S,/before=S,/after=S,/directory=S,/tag=S,",
                                                "Restore CONFIGURATION files."},
   {CMD_RESTOREFULL,     "restore-full",        ",/keepdata,/norecover,/verbose,/nochkver,/inclusive,/noninclusive,/pause,/vacuum,",
                                                ",/cid=S,/directory=S,/uid=S,/lsn=S,/port=N,/rp=S,/source=S,/until=D,/options=S,",  
                                                "Perform a restore full or the cluster."},
   {CMD_RESTOREPARTIAL,  "restore-partial",     ",/keepdata,/norecover,/verbose,/nochkver,/paused,/vacuum,",
                                                ",/cid=S,/db=S,/directory=S,/uid=S,/lsn=S,/newname=S,/port=N,/rp=S,/schema=S,/source=S,/table=S,/until=D,/options=S,",  
                                                "Perform a restore full or partial of databases,schemas or tables."},
   {CMD_RESTOREMETA,     "restore-meta",        ",/verbose,/overwrite,",
                                                ",/cid=S,/file=S,/uid=S,/directory=S,/tag=S,",
                                                "Restore METADATA sql file. The files are not executed."},
   {CMD_SAVE,            "save",                NULL,
                                                NULL,
                                                "Update configuration."},
   {CMD_SETCONFIG,       "set-config",          ",/session,",
                                                ",/timezone=S,/date_format=S,/prompt=S,/history=N,/bindir=S,",  
                                                "Modify local configuration."},
   {CMD_SETMAPPING,      "set-mapping",         ",/verbose,/force,",                                  
                                                ",/directory=S,/tablespace=S,",
                                                "For restore/duplicate, remap target tablespaces on different location."},
   {CMD_SETSOURCE,       "set-source",          ",/verbose,",                                  
                                                ",/directory=S,/blksize=S,",
                                                "Prepare source for restore without beeing connected to any cluster."},
   {CMD_SHOWBACKUP,      "show-backup",         ",/databases,/directories,/files,/indexes,/tables,",
                                                ",/uid=MS,/cid=N,/source=S,/piece=N,",
                                                "Display details of a backup."},
                                          
   {CMD_SHOWCLUSTER,     "show-cluster",        ",/backupdir,/blksize,/cfg,/compression,/db,/date_format,/delwal,/description,/full,/ip,/maxfiles,/maxwalfiles,/maxsize,/maxwalsize,/meta,/name,/pwd,/pgdata,/port,/repusr,/reppwd,/repopts,/usr,/waldir,",
                                                ",/parameter=S,",
                                                "Display cluster informations."},
   {CMD_STATCLUSTER,     "statistic-cluster",   NULL,
                                                ",/cid=N,/source=S,",
                                                "Display Backup cluster statistics."},
   {CMD_STATDEPOSIT,     "statistic-deposit",   NULL,
                                                NULL,
                                                "Display Deposit statistics."},
   {CMD_SHOWCONFIG,      "show-config",         ",/timezone,/date_format,/prompt,/history,/bindir,",
                                                NULL,                                                                                                 "Display configuration informations."},
   {CMD_SHOWDEPOSIT,     "show-deposit",        ",/description,/name,/host,/port,/usr,/pwd,/db,/version,",
                                                NULL,
                                                "Display DEPOSIT informations."},
   {CMD_SQL,             "sql",                 NULL,
                                                ",/cluster=S,/deposit=S,",
                                                "Execute a query on PostgreSQL database(Cluster or Deposit)"},
   {SYS_SHOWVARIABLE,    "@show-variables",     NULL,
                                                ",/name=S,",
                                                "Display internal variables."},
   {SYS_DEBUG,           "@debug",              ",/on,/off,",
                                                ",/file=S,",
                                                "Enable/Disable tracing."},
   {CMD_SWITCHWAL,       "switch-wal",          ",/nochkpt,/verbose,",
                                                NULL,
                                                "Invoke switch WAL."},
   {CMD_UPGRADEDEPOSIT,  "upgrade-deposit",     ",/verbose,/apply,",
                                                NULL,
                                                "Upgrade DEPOSIT database."},
   {CMD_VERIFYBACKUP,    "verify-backup",       ",/verbose,",
                                                ",/uid=S,/before=S,/after=S,",
                                                "Validate/Verify backups folder with DEPOSIT content."},
   {CMD_STATUS,          "status",              NULL,
                                                NULL,
                                                "Display current status of connections."},
   {0,NULL,NULL,NULL,NULL}
};
